<a href="https://colab.research.google.com/github/Changhyok/colab/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#예제로 배우는 파이썬 프로그래밍
reference: http://pythonstudy.xyz/python/article/402-numpy-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

In [1]:
import numpy as np

In [2]:
x=[1,2,3,4]
y=[[1,2,3],[4,5,6]]

In [3]:
a=np.array(x)

In [4]:
print(type(a))
print(a.shape,type(a.shape))
print(a.ndim,type(a.ndim))

<class 'numpy.ndarray'>
(4,) <class 'tuple'>
1 <class 'int'>


In [5]:
b=np.array([[1,2,3],[4,5,6]])

In [6]:
print(type(b))
print(b.shape)
print(b.ndim)

<class 'numpy.ndarray'>
(2, 3)
2


In [7]:
print(b[0][0])
print(b[0,0])
print(y[0][0])
#print(y[0,0])

1
1
1


In [8]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a=np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [11]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a=np.array(range(20)).reshape((4,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
a=np.array(range(1,10)).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
b=a[:2,:2]
print(b)

[[1 2]
 [4 5]]


In [15]:
b=a[1:,1:]
print(b)

[[5 6]
 [8 9]]


In [16]:
a=np.array(range(1,13)).reshape((3,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
b=a[[0,2],[1,3]]
print(b)

[ 2 12]


In [18]:
a=np.array(range(1,10)).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
b=np.array([[False,True,False],[True,False,True],[False,True,False]])
print(b)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [20]:
c=a[b]
print(type(c))
print(c.shape)
print(c.ndim)

<class 'numpy.ndarray'>
(4,)
1


In [21]:
b=a%2==0
print(b)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [22]:
c=a[b]
print(c)

[2 4 6 8]


In [23]:
c=a[a%2==0]
print(c)

[2 4 6 8]


In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [25]:
c=a+b
print(c)
c=np.add(a,b)
print(c)

[5 7 9]
[5 7 9]


In [26]:
c=a-b
print(c)
c=np.subtract(a,b)
print(c)

[-3 -3 -3]
[-3 -3 -3]


In [27]:
c=a*b
print(c)
c=np.multiply(a,b)
print(c)

[ 4 10 18]
[ 4 10 18]


In [28]:
c=a/b
print(c)
c=np.divide(a,b)
print(c)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [29]:
a=np.array(range(1,5)).reshape((2,2))
b=np.array(range(5,9)).reshape((2,2))

In [30]:
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [31]:
1*5+2*7

19

In [32]:
x=np.sum(a)
print(x)
x=np.sum(a,axis=0)
print(x)
x=np.sum(a,axis=1)
print(x)

10
[4 6]
[3 7]


In [33]:
x=np.prod(a)
print(x)
x=np.prod(a,axis=0)
print(x)
x=np.prod(a,axis=1)
print(x)

24
[3 8]
[ 2 12]
