<a href="https://colab.research.google.com/github/Changhyok/colab/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#예제로 배우는 파이썬 프로그래밍

reference: 

http://pythonstudy.xyz/python/article/402-numpy-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

In [1]:
import numpy as np

In [2]:
x=[1,2,3,4]
y=[[1,2,3],[4,5,6]]

In [3]:
a=np.array(x)

In [4]:
print(type(a))
print(a.shape,type(a.shape))
print(a.ndim,type(a.ndim))

<class 'numpy.ndarray'>
(4,) <class 'tuple'>
1 <class 'int'>


In [5]:
b=np.array([[1,2,3],[4,5,6]])

In [6]:
print(type(b))
print(b.shape)
print(b.ndim)

<class 'numpy.ndarray'>
(2, 3)
2


In [7]:
print(b[0][0])
print(b[0,0])
print(y[0][0])
#print(y[0,0])

1
1
1


In [8]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a=np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [11]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a=np.array(range(20)).reshape((4,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
a=np.array(range(1,10)).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
b=a[:2,:2]
print(b)

[[1 2]
 [4 5]]


In [15]:
b=a[1:,1:]
print(b)

[[5 6]
 [8 9]]


In [16]:
a=np.array(range(1,13)).reshape((3,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
b=a[[0,2],[1,3]]
print(b)

[ 2 12]


In [18]:
a=np.array(range(1,10)).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
b=np.array([[False,True,False],[True,False,True],[False,True,False]])
print(b)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [20]:
c=a[b]
print(type(c))
print(c.shape)
print(c.ndim)

<class 'numpy.ndarray'>
(4,)
1


In [21]:
b=a%2==0
print(b)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [22]:
c=a[b]
print(c)

[2 4 6 8]


In [23]:
c=a[a%2==0]
print(c)

[2 4 6 8]


In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [25]:
c=a+b
print(c)
c=np.add(a,b)
print(c)

[5 7 9]
[5 7 9]


In [26]:
c=a-b
print(c)
c=np.subtract(a,b)
print(c)

[-3 -3 -3]
[-3 -3 -3]


In [27]:
c=a*b
print(c)
c=np.multiply(a,b)
print(c)

[ 4 10 18]
[ 4 10 18]


In [28]:
c=a/b
print(c)
c=np.divide(a,b)
print(c)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [29]:
a=np.array(range(1,5)).reshape((2,2))
b=np.array(range(5,9)).reshape((2,2))

In [30]:
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [31]:
1*5+2*7

19

In [32]:
x=np.sum(a)
print(x)
x=np.sum(a,axis=0)
print(x)
x=np.sum(a,axis=1)
print(x)

10
[4 6]
[3 7]


In [33]:
x=np.prod(a)
print(x)
x=np.prod(a,axis=0)
print(x)
x=np.prod(a,axis=1)
print(x)

24
[3 8]
[ 2 12]


#넘파이 기초 정리

reference:

https://doorbw.tistory.com/171

In [39]:
data1=[1,2,3,4,5]
print(data1)
print(type(data1))
print(len(data1))

[1, 2, 3, 4, 5]
<class 'list'>
5


In [35]:
data2=[1,2,3,3.5,4]
print(data2)

[1, 2, 3, 3.5, 4]


In [41]:
arr1=np.array(data1)
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64


In [43]:
arr2=np.array(data2)
print(arr2)
print(type(arr2))
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

[1.  2.  3.  3.5 4. ]
<class 'numpy.ndarray'>
(5,)
1
float64


In [46]:
arr4=np.array(range(1,13)).reshape((4,3))
print(arr4)
print(arr4.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a=np.arange(3,10)
print(type(a),a)

<class 'numpy.ndarray'> [3 4 5 6 7 8 9]


In [55]:
a=range(3,10)
print(type(a),a)

<class 'range'> range(3, 10)


In [61]:
a=np.arange(1,7).reshape(2,3)
print(type(a))
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


In [63]:
b=np.arange(10,16).reshape(2,3)
print(type(b))
print(b)
print(b.shape)
print(b.ndim)
print(b.dtype)

<class 'numpy.ndarray'>
[[10 11 12]
 [13 14 15]]
(2, 3)
2
int64


In [64]:
a+b

array([[11, 13, 15],
       [17, 19, 21]])

In [65]:
a-b

array([[-9, -9, -9],
       [-9, -9, -9]])

In [66]:
a*b

array([[10, 22, 36],
       [52, 70, 90]])

In [67]:
a/b

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [69]:
c=np.array([10,11,12])
print(c)
print(c.shape)

[10 11 12]
(3,)


In [70]:
a+c

array([[11, 13, 15],
       [14, 16, 18]])

In [71]:
a*c

array([[10, 22, 36],
       [40, 55, 72]])

In [72]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [74]:
a=np.arange(10)
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [75]:
a[0]

0

In [76]:
a[3]

3

In [77]:
a[3:9]

array([3, 4, 5, 6, 7, 8])

In [78]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
b=np.arange(1,13).reshape(3,4)
print(b)
print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [81]:
b[0,0]

1

In [82]:
b[2,:]

array([ 9, 10, 11, 12])

In [83]:
b[2,3]

12

In [84]:
b[:,3]

array([ 4,  8, 12])

In [85]:
names=np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
print(names)

['Beomwoo' 'Beomwoo' 'Kim' 'Joan' 'Lee' 'Beomwoo' 'Park' 'Beomwoo']


In [86]:
print(names.shape)

(8,)


In [88]:
data=np.random.randn(8,4)
print(data)
print(data.shape)

[[-1.02200426 -0.37114979 -1.37740795 -0.25829838]
 [-0.1491284   1.79605617  1.57896411  0.38632261]
 [ 1.99891803  0.11586452 -0.59728267 -0.67690885]
 [ 0.15155536  0.47307666  0.21244445  0.07795256]
 [ 0.60125796  0.5820415  -0.06480611 -0.73421319]
 [ 0.56685984  1.06313195  0.62801907 -0.41134073]
 [-2.02037394 -1.65450499 -0.73665298 -3.18735523]
 [ 1.11203345  0.43817925 -0.21899706 -1.22496326]]
(8, 4)


In [89]:
names_Beomwoo_mask=names=='Beomwoo'
print(names_Beomwoo_mask)

[ True  True False False False  True False  True]


In [90]:
data[names_Beomwoo_mask,:]

array([[-1.02200426, -0.37114979, -1.37740795, -0.25829838],
       [-0.1491284 ,  1.79605617,  1.57896411,  0.38632261],
       [ 0.56685984,  1.06313195,  0.62801907, -0.41134073],
       [ 1.11203345,  0.43817925, -0.21899706, -1.22496326]])

In [91]:
data[names=='Kim',:]

array([[ 1.99891803,  0.11586452, -0.59728267, -0.67690885]])

In [92]:
data[(names=='Kim')|(names=='Park'),:]

array([[ 1.99891803,  0.11586452, -0.59728267, -0.67690885],
       [-2.02037394, -1.65450499, -0.73665298, -3.18735523]])

In [93]:
data[:,0]<0

array([ True,  True, False, False, False, False,  True, False])

In [94]:
data[data[:,0]<0,:]

array([[-1.02200426, -0.37114979, -1.37740795, -0.25829838],
       [-0.1491284 ,  1.79605617,  1.57896411,  0.38632261],
       [-2.02037394, -1.65450499, -0.73665298, -3.18735523]])

In [95]:
data[data[:,0]<0,2:4]

array([[-1.37740795, -0.25829838],
       [ 1.57896411,  0.38632261],
       [-0.73665298, -3.18735523]])

In [96]:
data[data[:,0]<0,2:4]=0
print(data)

[[-1.02200426 -0.37114979  0.          0.        ]
 [-0.1491284   1.79605617  0.          0.        ]
 [ 1.99891803  0.11586452 -0.59728267 -0.67690885]
 [ 0.15155536  0.47307666  0.21244445  0.07795256]
 [ 0.60125796  0.5820415  -0.06480611 -0.73421319]
 [ 0.56685984  1.06313195  0.62801907 -0.41134073]
 [-2.02037394 -1.65450499  0.          0.        ]
 [ 1.11203345  0.43817925 -0.21899706 -1.22496326]]


In [97]:
a=np.random.randn(5,3)
print(a)

[[-0.24391926 -0.48957129  0.66827835]
 [ 1.00818183 -0.17804492  0.23992597]
 [-0.03575236  0.18557971 -0.47251012]
 [-1.26561411  0.26836528 -0.86128749]
 [ 2.07410809  1.96675344  0.12048208]]


In [98]:
np.abs(a)

array([[0.24391926, 0.48957129, 0.66827835],
       [1.00818183, 0.17804492, 0.23992597],
       [0.03575236, 0.18557971, 0.47251012],
       [1.26561411, 0.26836528, 0.86128749],
       [2.07410809, 1.96675344, 0.12048208]])

In [99]:
np.sqrt(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[       nan,        nan, 0.81748294],
       [1.00408258,        nan, 0.48982239],
       [       nan, 0.43078963,        nan],
       [       nan, 0.51803984,        nan],
       [1.44017641, 1.40240987, 0.34710528]])

In [100]:
np.square(a)

array([[5.94966051e-02, 2.39680044e-01, 4.46595953e-01],
       [1.01643059e+00, 3.16999949e-02, 5.75644716e-02],
       [1.27823100e-03, 3.44398283e-02, 2.23265818e-01],
       [1.60177908e+00, 7.20199239e-02, 7.41816139e-01],
       [4.30192438e+00, 3.86811909e+00, 1.45159313e-02]])

In [101]:
np.exp(a)

array([[0.7835509 , 0.61288909, 1.9508757 ],
       [2.74061357, 0.83690483, 1.27115504],
       [0.96487921, 1.20391616, 0.6234354 ],
       [0.28206602, 1.30782478, 0.42261762],
       [7.957446  , 7.14743419, 1.12804052]])

In [102]:
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[        nan,         nan, -0.4030505 ],
       [ 0.00814854,         nan, -1.42742486],
       [        nan, -1.68427079,         nan],
       [        nan, -1.31540624,         nan],
       [ 0.72953123,  0.67638418, -2.11625426]])

In [103]:
np.log10(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([[        nan,         nan, -0.17504261],
       [ 0.00353886,         nan, -0.61992274],
       [        nan, -0.73146951,         nan],
       [        nan, -0.57127367,         nan],
       [ 0.31683139,  0.29374992, -0.91907755]])

In [104]:
np.log2(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([[        nan,         nan, -0.58147896],
       [ 0.01175585,         nan, -2.05933876],
       [        nan, -2.42988912,         nan],
       [        nan, -1.89773006,         nan],
       [ 1.05249108,  0.97581611, -3.05310953]])

In [105]:
np.sign(a)

array([[-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.]])

In [106]:
np.ceil(a)

array([[-0., -0.,  1.],
       [ 2., -0.,  1.],
       [-0.,  1., -0.],
       [-1.,  1., -0.],
       [ 3.,  2.,  1.]])

In [107]:
np.floor(a)

array([[-1., -1.,  0.],
       [ 1., -1.,  0.],
       [-1.,  0., -1.],
       [-2.,  0., -1.],
       [ 2.,  1.,  0.]])

In [108]:
np.isnan(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [109]:
np.isnan(np.log(a))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[ True,  True, False],
       [False,  True, False],
       [ True, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [110]:
np.isinf(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [111]:
np.cos(a)

array([[ 0.9703989 ,  0.88253454,  0.78488962],
       [ 0.53339953,  0.98419183,  0.97135557],
       [ 0.99936095,  0.98282945,  0.89042868],
       [ 0.30046697,  0.96420564,  0.65146121],
       [-0.48232925, -0.38569142,  0.99275081]])

In [112]:
np.tanh(a)

array([[-0.23919422, -0.4538761 ,  0.58384624],
       [ 0.76500896, -0.17618714,  0.23542582],
       [-0.03573713,  0.18347821, -0.44022522],
       [-0.85260449,  0.26210307, -0.69692043],
       [ 0.96890593,  0.96160183,  0.11990247]])

In [114]:
b=np.random.randn(5,3)
print(b)

[[ 0.00900124 -0.80350477  1.39400653]
 [-1.56304709 -0.00321759  0.55201966]
 [ 0.11200229  0.84034338  1.5625656 ]
 [ 0.26934367  0.25825375  0.34613173]
 [ 0.14966122 -0.33997195 -1.11190808]]


In [115]:
np.multiply(a,b)

array([[-2.19557671e-03,  3.93372864e-01,  9.31584382e-01],
       [-1.57583567e+00,  5.72875988e-04,  1.32443853e-01],
       [-4.00434583e-03,  1.55950679e-01, -7.38328068e-01],
       [-3.40885145e-01,  6.93063413e-02, -2.98118931e-01],
       [ 3.10413547e-01, -6.68641006e-01, -1.33964997e-01]])

In [116]:
np.maximum(a,b)

array([[ 0.00900124, -0.48957129,  1.39400653],
       [ 1.00818183, -0.00321759,  0.55201966],
       [ 0.11200229,  0.84034338,  1.5625656 ],
       [ 0.26934367,  0.26836528,  0.34613173],
       [ 2.07410809,  1.96675344,  0.12048208]])

In [117]:
np.sum(a)

2.984975195930688

In [118]:
np.sum(a,axis=1)

array([-0.06521219,  1.07006287, -0.32268277, -1.85853632,  4.16134361])

In [120]:
np.sum(a,axis=0)

array([ 1.53700419,  1.75308222, -0.30511121])

In [121]:
np.mean(a)

0.1989983463953792

In [122]:
np.mean(a,axis=0)

array([ 0.30740084,  0.35061644, -0.06102224])

In [123]:
np.std(a)

0.8987628889215779

In [124]:
np.min(a,axis=1)

array([-0.48957129, -0.17804492, -0.47251012, -1.26561411,  0.12048208])

In [125]:
np.argmin(a)

9

In [126]:
a

array([[-0.24391926, -0.48957129,  0.66827835],
       [ 1.00818183, -0.17804492,  0.23992597],
       [-0.03575236,  0.18557971, -0.47251012],
       [-1.26561411,  0.26836528, -0.86128749],
       [ 2.07410809,  1.96675344,  0.12048208]])

In [127]:
np.argmax(a,axis=0)

array([4, 4, 0])

In [128]:
np.cumsum(a)

array([-0.24391926, -0.73349054, -0.06521219,  0.94296963,  0.76492471,
        1.00485068,  0.96909832,  1.15467803,  0.68216791, -0.58344621,
       -0.31508093, -1.17636841,  0.89773968,  2.86449312,  2.9849752 ])

In [129]:
np.cumprod(a)

array([-2.43919259e-01,  1.19415865e-01,  7.98030374e-02,  8.04559720e-02,
       -1.43247774e-02, -3.43688613e-03,  1.22876778e-04,  2.28034367e-05,
       -1.07748547e-05,  1.36368082e-05,  3.65964586e-06, -3.15200719e-06,
       -6.53760363e-06, -1.28578544e-05, -1.54914103e-06])

In [130]:
np.cumsum(a,axis=1)

array([[-0.24391926, -0.73349054, -0.06521219],
       [ 1.00818183,  0.8301369 ,  1.07006287],
       [-0.03575236,  0.14982735, -0.32268277],
       [-1.26561411, -0.99724883, -1.85853632],
       [ 2.07410809,  4.04086153,  4.16134361]])

In [132]:
np.cumprod(a,axis=1)

array([[-2.43919259e-01,  1.19415865e-01,  7.98030374e-02],
       [ 1.00818183e+00, -1.79501657e-01, -4.30671093e-02],
       [-3.57523565e-02, -6.63491191e-03,  3.13506305e-03],
       [-1.26561411e+00, -3.39646887e-01,  2.92533614e-01],
       [ 2.07410809e+00,  4.07925922e+00,  4.91477631e-01]])

In [133]:
a

array([[-0.24391926, -0.48957129,  0.66827835],
       [ 1.00818183, -0.17804492,  0.23992597],
       [-0.03575236,  0.18557971, -0.47251012],
       [-1.26561411,  0.26836528, -0.86128749],
       [ 2.07410809,  1.96675344,  0.12048208]])

In [134]:
np.sort(a)

array([[-0.48957129, -0.24391926,  0.66827835],
       [-0.17804492,  0.23992597,  1.00818183],
       [-0.47251012, -0.03575236,  0.18557971],
       [-1.26561411, -0.86128749,  0.26836528],
       [ 0.12048208,  1.96675344,  2.07410809]])

In [141]:
np.sort(a)[::-1]

array([[ 0.12048208,  1.96675344,  2.07410809],
       [-1.26561411, -0.86128749,  0.26836528],
       [-0.47251012, -0.03575236,  0.18557971],
       [-0.17804492,  0.23992597,  1.00818183],
       [-0.48957129, -0.24391926,  0.66827835]])

In [142]:
np.sort(a,axis=0)

array([[-1.26561411, -0.48957129, -0.86128749],
       [-0.24391926, -0.17804492, -0.47251012],
       [-0.03575236,  0.18557971,  0.12048208],
       [ 1.00818183,  0.26836528,  0.23992597],
       [ 2.07410809,  1.96675344,  0.66827835]])